name: Environment updates pipeline
# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check_change:
    name: Plan env update
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Plan update vs running env
      id: plan-environment
      uses: TomerAdmon/torque-plan-environment@4153df76129eb5d67cb66648e088bb5768fb9abc
      with:
        space: Production
        torque_token: ${{ secrets.TORQUE_TOKEN }}
        environment_id: zDsSfW32L3MW
        torque_hostname: https://review3.qualilabs.net/
        env_file_path: environments/production.yaml
