name: Terraform module pipeline
# Controls when the workflow will run
on:
# Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    paths:
      - 'terraform/create-ec2-instance/*.*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Upload_Artifact_To_S3:
    name: Upload the latest version of the webgame to S3
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
      name: Upload Webgame folder
      with:
        args:  --delete
      env:
        AWS_S3_BUCKET: 'torque-prod-cfn-assets'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1
        SOURCE_DIR: 'WebApps/TetrisJS'      # optional: defaults to entire repository
        DEST_DIR: 'public-assets'
  Test_On_Torque_Environment:
    needs: Upload_Artifact_To_S3
    name: Test the updated webgame on a Torque Environment
    runs-on: ubuntu-latest
    steps:
    - name: Start Environment from Blueprint
      id: start-environment
      uses: QualiTorque/torque-start-environment@v1
      with:
        space: 03-Live
        torque_token: ${{ secrets.TORQUE_TOKEN }}
        blueprint_name: Webgame on S3 (TF)
        repository_name: ProductionBPs
        inputs: 'Name=webapp-gh, Name Prefix=torque, AWS Region=us-west-1'
        timeout: 15
        duration: 15
    - name: Execute unit tests
      id: test-app
      run: |
        echo "Running tests against environment with id: ${{ steps.start-environment.outputs.environment_id }}"
        curl -I https://torque-webapp-gh-${{ steps.start-environment.outputs.environment_id }}.s3.us-west-1.amazonaws.com/index.html | head -n 1
        sleep 600
    - name: End Environment
      uses: QualiTorque/torque-end-environment@v1
      with:
        space: 03-Live
        torque_token: ${{ secrets.TORQUE_TOKEN }}
        environment_id: ${{ steps.start-environment.outputs.environment_id }}
